### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by ghost** [twonk/RGBPongClock#1]
Sorry if this is doen't fit in here, but I want to know if can use the Code without an ethernet shield, because I don't have an ethernet connection in my room. I also want to know how   (randomSeed(analogRead(8));
  //setTime(10,12,0,13,9,2013); ) to set the time on this code 11:30 17.04.2015. Please help me. Is an microphone requiered on this project?

**Comment by twonk** [comment]
Hi,
You dont need an ethernet shield, must admit that I havent tried running the code without one, but dont think it will be a problem.  You'll get a timeout when the code tries to connect to the internet to get the weather results, but once its done that and failed it should carry on as normal.  Network is only used for the weather pull, so you'll not get that.

The randomSeed(analogRead(8)) line just sets up the system with a starting point for the random number generator.

To set the time you'd do setTime(11,39,0,17,4,2015);
see here:  http://playground.arduino.cc/code/time 

Microphone is required if you want the spectrum analyser mode to work.

Have fun!

**Comment by ghost** [comment]
Thanks for your help!
