### ISSUE TITLE
Question about Wiring

### ISSUE THREAD

**Issue by ghost** [twonk/RGBPongClock#3]
Here are my standard informations about connecting an Arduino Mega ( I use an Arduino Mega Rev 3 for this) to an DS 1307, an Analog Microphone or an 16x32 RGB Matrix. But there are more GND Inputs on the Mega required than there actually are. These are the informations about wiring the DS 1307 and the Microphone
    Píns   Pins on the Patine
DS1307          GND         GND
                    5V                  5V
                    Digital Pin 4   Digital Pin 4
                    Digital Pin 5   Digital Pin 5
Microphone  AO                  AI
                    GND         GND
                    VCL                 Power

And this is about wiring the RGB Matrix
        R0           2
    G0           3
    B0           4
    GND  GND
    R1           5
    G1           6
    B1           7
    GND GND
    A           A0
    B           A1
    C           A2
    D           A3
    CLK         11
    STB         10
    OE          9
    GND GND
Can you tell me how your wired it or which pins ar useless for the clock or spectrum analyzer or which pin can get on another Input pin on the Mega?
Grateful,
Revedar

**Comment by ghost** [comment]
I found this Graphic on the Adafruit website: https://learn.adafruit.com/system/assets/assets/000/023/826/medium800/led_matrix_plug2.png?1426392350

**Comment by ghost** [comment]
Sorry. I solved it with this :http://cdn.instructables.com/FDY/DDW9/HQVLDSGJ/FDYDDW9HQVLDSGJ.LARGE.jpg

**Comment by twonk** [comment]
Apologies for not getting back to you sooner.  Here are all of the connections in use:

For the grounds, you'll need to combine some of them together and then attache to a ground pin. 

**RTC**
SDA -> D20
SCL -> D21
MOS -> not connected
VCC -> 5v
GND -> GND

**Button 1** 
D2 and GND

**Button 2**
D3 and GND

**Microphone board**
VCC ->  3.3v & AREF
ANALOG OUT -> A0
GND->GND

**Matrix Connector**
![Adafruit Image](https://learn.adafruit.com/system/assets/assets/000/023/826/medium800/led_matrix_plug2.png?1426392350)

| Left | Right |
| --- | --- |
| G1 ->  25 | R1 ->  24 |
| GND | B1 ->  26 |
| G2 -> 28 | R2 -> 27 |
| GND | B2 -> 29 |
| B -> A1 | A -> A4 |
| D -> GND | C -> A2 |
| LAT -> A3 | CLK -> D12 |
| GND | OE -> D8 |

**Comment by ghost** [comment]
Last question: Do you use 2 or 4 pin buttons?
Sorry that i have so much questions i just came in the last 9 moth into electronics and in school we will just talk about this theme in 2 year and the next opportunity to learn programming for me is on the university and then the also the next time when i have enough time to come into coding.

**Comment by twonk** [comment]
No problem at all.
I used two pin buttons, but usually on four pin buttons the pins are in two
pairs, so as long as you use one pin from each side it will be fine.
These are great projects to get started with.  There is nothing better than
an LED display!

**Comment by ghost** [comment]
I agree :D
